  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_AUTH_API_URL: http://auth-service:3001/api
        VITE_USER_API_URL: http://user-service:3002/users
        VITE_POST_API_URL: http://post-service:3003/api
    container_name: frontend
    ports:
      - "5173:80"
    networks:
      - backend
    depends_on:
      - auth-service
      - user-service
      - post-service
